import { ThemeDefinition } from "@/types/theme";

export const THEMES: ThemeDefinition[] = [
  // ================= MODERN (HIỆN TẠI) =================
  {
    id: "cyberpunk",
    name: "Cyberpunk Neon",
    shortName: "Neon",
    category: "current",
    description: "Ánh sáng neon tương lai với dải màu tím cyan rực rỡ",
    previewColors: ["#06b6d4", "#9333ea"],
    bgType: "mesh",
    canvasBg: "#0a0e1a",
    meshColors: ["#06b6d4", "#9333ea"],
    panelFill: "rgba(15, 23, 42, 0.88)",
    panelBorder: "rgba(6, 182, 212, 0.35)",
    panelRadius: 28,
    fontHeading: "'Plus Jakarta Sans', 'Be Vietnam Pro', sans-serif",
    fontBody: "'Plus Jakarta Sans', 'Be Vietnam Pro', sans-serif",
    titleColor: "#38bdf8",
    subtitleColor: "rgba(255, 255, 255, 0.7)",
    textPrimary: "#ffffff",
    textMuted: "rgba(255, 255, 255, 0.65)",
    badgeBg: "#06b6d4",
    badgeText: "#020617",
    dayColor: "#e0f2fe",
    dayBorderColor: "rgba(6, 182, 212, 0.25)",
    timeColor: "#94a3b8",
    timeBorderColor: "rgba(255, 255, 255, 0.1)",
    cellFill: "rgba(30, 41, 59, 0.75)",
    cellBorder: "rgba(255, 255, 255, 0.12)",
    cellEmptyFill: "rgba(15, 23, 42, 0.4)",
    cellEmptyBorder: "rgba(255, 255, 255, 0.06)",
    subjectColor: "#ffffff",
    teacherColor: "#38bdf8",
    highlightDefault: "#f0abfc",
    uiAccentBg: "bg-cyan-500 text-black",
    uiCardBg: "bg-slate-800/80 border-white/10",
    uiBorder: "border-cyan-500/30",
  },
  {
    id: "sunset",
    name: "Sunset Bliss",
    shortName: "Sunset",
    category: "current",
    description: "Sắc tím hồng hoàng hôn ấm áp và lãng mạn",
    previewColors: ["#f43f5e", "#f97316"],
    bgType: "mesh",
    canvasBg: "#1f092b",
    meshColors: ["#f43f5e", "#f97316"],
    panelFill: "rgba(47, 7, 67, 0.9)",
    panelBorder: "rgba(244, 63, 94, 0.35)",
    panelRadius: 28,
    fontHeading: "'Plus Jakarta Sans', 'Be Vietnam Pro', sans-serif",
    fontBody: "'Plus Jakarta Sans', 'Be Vietnam Pro', sans-serif",
    titleColor: "#fda4af",
    subtitleColor: "rgba(255, 255, 255, 0.75)",
    textPrimary: "#ffffff",
    textMuted: "rgba(255, 255, 255, 0.65)",
    badgeBg: "#f97316",
    badgeText: "#ffffff",
    dayColor: "#fed7aa",
    dayBorderColor: "rgba(249, 115, 22, 0.3)",
    timeColor: "#f472b6",
    timeBorderColor: "rgba(255, 255, 255, 0.12)",
    cellFill: "rgba(255, 255, 255, 0.1)",
    cellBorder: "rgba(255, 255, 255, 0.18)",
    cellEmptyFill: "rgba(255, 255, 255, 0.04)",
    cellEmptyBorder: "rgba(255, 255, 255, 0.07)",
    subjectColor: "#ffffff",
    teacherColor: "#fdba74",
    highlightDefault: "#fb923c",
    uiAccentBg: "bg-orange-500 text-white",
    uiCardBg: "bg-purple-950/80 border-white/10",
    uiBorder: "border-pink-500/30",
  },
  {
    id: "oceanic",
    name: "Deep Ocean",
    shortName: "Ocean",
    category: "current",
    description: "Màu xanh ngọc lam đại dương sâu thẳm mát mẻ",
    previewColors: ["#0d9488", "#2563eb"],
    bgType: "mesh",
    canvasBg: "#081321",
    meshColors: ["#0d9488", "#2563eb"],
    panelFill: "rgba(12, 25, 41, 0.9)",
    panelBorder: "rgba(45, 212, 191, 0.28)",
    panelRadius: 28,
    fontHeading: "'Plus Jakarta Sans', 'Be Vietnam Pro', sans-serif",
    fontBody: "'Plus Jakarta Sans', 'Be Vietnam Pro', sans-serif",
    titleColor: "#5eead4",
    subtitleColor: "rgba(224, 242, 254, 0.75)",
    textPrimary: "#f0fdfa",
    textMuted: "rgba(204, 251, 241, 0.65)",
    badgeBg: "#14b8a6",
    badgeText: "#020617",
    dayColor: "#a5f3fc",
    dayBorderColor: "rgba(20, 184, 166, 0.3)",
    timeColor: "#99f6e4",
    timeBorderColor: "rgba(255, 255, 255, 0.1)",
    cellFill: "rgba(15, 34, 56, 0.75)",
    cellBorder: "rgba(255, 255, 255, 0.14)",
    cellEmptyFill: "rgba(8, 20, 36, 0.4)",
    cellEmptyBorder: "rgba(255, 255, 255, 0.06)",
    subjectColor: "#ffffff",
    teacherColor: "#5eead4",
    highlightDefault: "#2dd4bf",
    uiAccentBg: "bg-teal-400 text-black",
    uiCardBg: "bg-slate-900/80 border-teal-500/20",
    uiBorder: "border-teal-500/30",
  },
  {
    id: "light_fresh",
    name: "Light & Fresh",
    shortName: "Refreshing",
    category: "current",
    description: "Nền sáng thanh lịch, tinh tế và dễ theo dõi",
    previewColors: ["#6366f1", "#ec4899"],
    bgType: "mesh",
    canvasBg: "#f1f5f9",
    meshColors: ["#818cf8", "#f472b6"],
    panelFill: "rgba(255, 255, 255, 0.96)",
    panelBorder: "#cbd5e1",
    panelRadius: 28,
    fontHeading: "'Plus Jakarta Sans', 'Be Vietnam Pro', sans-serif",
    fontBody: "'Plus Jakarta Sans', 'Be Vietnam Pro', sans-serif",
    titleColor: "#1e293b",
    subtitleColor: "#64748b",
    textPrimary: "#0f172a",
    textMuted: "#64748b",
    badgeBg: "#4f46e5",
    badgeText: "#ffffff",
    dayColor: "#334155",
    dayBorderColor: "#cbd5e1",
    timeColor: "#64748b",
    timeBorderColor: "#e2e8f0",
    cellFill: "#ffffff",
    cellBorder: "#cbd5e1",
    cellEmptyFill: "#f8fafc",
    cellEmptyBorder: "#e2e8f0",
    subjectColor: "#0f172a",
    teacherColor: "#4f46e5",
    highlightDefault: "#818cf8",
    uiAccentBg: "bg-indigo-600 text-white",
    uiCardBg: "bg-white border-slate-200",
    uiBorder: "border-indigo-400/30",
  },

  // ================= CLASSIC (CỔ ĐIỂN HỌC ĐƯỜNG) =================
  {
    id: "classic_chalkboard",
    name: "Bảng Phấn Học Đường",
    shortName: "Blackboard",
    category: "classic",
    description: "Mặt bảng xanh lá sẫm, nét phấn trắng & vàng hoài niệm của lớp học",
    previewColors: ["#15803d", "#facc15"],
    bgType: "chalkboard",
    canvasBg: "#12281e",
    panelFill: "#163426",
    panelBorder: "#94a3b8", // viền nhôm bảng
    panelRadius: 20,
    fontHeading: "'Baloo 2', 'Be Vietnam Pro', cursive, sans-serif",
    fontBody: "'Be Vietnam Pro', 'Plus Jakarta Sans', sans-serif",
    titleColor: "#fef08a", // phấn vàng
    subtitleColor: "#e2e8f0",
    textPrimary: "#f8fafc", // phấn trắng
    textMuted: "#cbd5e1",
    badgeBg: "#facc15",
    badgeText: "#14532d",
    dayColor: "#fef08a",
    dayBorderColor: "rgba(255, 255, 255, 0.3)",
    timeColor: "#cbd5e1",
    timeBorderColor: "rgba(255, 255, 255, 0.15)",
    cellFill: "rgba(29, 66, 49, 0.9)",
    cellBorder: "rgba(255, 255, 255, 0.25)",
    cellEmptyFill: "rgba(22, 52, 38, 0.5)",
    cellEmptyBorder: "rgba(255, 255, 255, 0.1)",
    subjectColor: "#ffffff",
    teacherColor: "#fde047",
    highlightDefault: "#4ade80",
    uiAccentBg: "bg-yellow-400 text-green-950",
    uiCardBg: "bg-emerald-950/80 border-emerald-600/30",
    uiBorder: "border-yellow-400/40",
  },
  {
    id: "classic_notebook",
    name: "Vở Ô Ly Học Sinh",
    shortName: "Notebook",
    category: "classic",
    description: "Nền giấy tập kẻ ô vuông mờ, nét mực bút bi xanh & tiêu đề mực đỏ thân quen",
    previewColors: ["#dc2626", "#2563eb"],
    bgType: "notebook",
    canvasBg: "#f8fafc",
    panelFill: "#ffffff",
    panelBorder: "#93c5fd",
    panelRadius: 18,
    fontHeading: "'Baloo 2', 'Be Vietnam Pro', cursive, sans-serif",
    fontBody: "'Be Vietnam Pro', 'Plus Jakarta Sans', sans-serif",
    titleColor: "#dc2626", // mực đỏ chấm điểm
    subtitleColor: "#475569",
    textPrimary: "#1e3a8a", // mực bút bi xanh
    textMuted: "#64748b",
    badgeBg: "#dc2626",
    badgeText: "#ffffff",
    dayColor: "#1d4ed8",
    dayBorderColor: "#bfdbfe",
    timeColor: "#475569",
    timeBorderColor: "#e2e8f0",
    cellFill: "#f0f7ff",
    cellBorder: "#93c5fd",
    cellEmptyFill: "#ffffff",
    cellEmptyBorder: "#e2e8f0",
    subjectColor: "#1e3a8a",
    teacherColor: "#b91c1c",
    highlightDefault: "#fde047",
    uiAccentBg: "bg-red-600 text-white",
    uiCardBg: "bg-blue-50/80 border-blue-200",
    uiBorder: "border-blue-400/30",
  },

  // ================= BLACK & WHITE (ĐEN TRẮNG - IN ẤN) =================
  {
    id: "bw_clean",
    name: "Monochrome Print (In A4)",
    shortName: "White",
    category: "bw",
    description: "Tối ưu in ấn ra giấy A4, nền trắng tinh, viền đen sắc sảo, không tốn mực màu",
    previewColors: ["#000000", "#ffffff"],
    bgType: "clean",
    canvasBg: "#ffffff",
    panelFill: "#ffffff",
    panelBorder: "#000000",
    panelRadius: 16,
    shadowOffset: 0,
    fontHeading: "'Plus Jakarta Sans', 'Be Vietnam Pro', sans-serif",
    fontBody: "'Be Vietnam Pro', 'Plus Jakarta Sans', sans-serif",
    titleColor: "#000000",
    subtitleColor: "#4b5563",
    textPrimary: "#000000",
    textMuted: "#4b5563",
    badgeBg: "#000000",
    badgeText: "#ffffff",
    dayColor: "#000000",
    dayBorderColor: "#000000",
    timeColor: "#1f2937",
    timeBorderColor: "#9ca3af",
    cellFill: "#ffffff",
    cellBorder: "#000000",
    cellEmptyFill: "#f9fafb",
    cellEmptyBorder: "#d1d5db",
    subjectColor: "#000000",
    teacherColor: "#374151",
    highlightDefault: "#e5e7eb",
    uiAccentBg: "bg-black text-white",
    uiCardBg: "bg-white border-black",
    uiBorder: "border-black",
  },
  {
    id: "bw_dark",
    name: "Dark Charcoal Minimal",
    shortName: "Black",
    category: "bw",
    description: "Tối giản đơn sắc sang trọng, tương phản than chì đậm và trắng bạc",
    previewColors: ["#18181b", "#71717a"],
    bgType: "dark",
    canvasBg: "#09090b",
    panelFill: "#18181b",
    panelBorder: "#3f3f46",
    panelRadius: 24,
    fontHeading: "'Plus Jakarta Sans', 'Be Vietnam Pro', sans-serif",
    fontBody: "'Be Vietnam Pro', 'Plus Jakarta Sans', sans-serif",
    titleColor: "#fafafa",
    subtitleColor: "#a1a1aa",
    textPrimary: "#f4f4f5",
    textMuted: "#a1a1aa",
    badgeBg: "#fafafa",
    badgeText: "#09090b",
    dayColor: "#e4e4e7",
    dayBorderColor: "#3f3f46",
    timeColor: "#a1a1aa",
    timeBorderColor: "#27272a",
    cellFill: "#27272a",
    cellBorder: "#3f3f46",
    cellEmptyFill: "#141416",
    cellEmptyBorder: "#27272a",
    subjectColor: "#ffffff",
    teacherColor: "#d4d4d8",
    highlightDefault: "#52525b",
    uiAccentBg: "bg-zinc-200 text-zinc-900",
    uiCardBg: "bg-zinc-900 border-zinc-700",
    uiBorder: "border-zinc-500",
  },

  // ================= HAND-DRAWN (PHONG CÁCH VẼ TAY) =================
  {
    id: "hand_drawn",
    name: "Hand-Drawn Sketch (Giấy Sáng)",
    shortName: "Hand-drawn",
    category: "handdrawn",
    description: "Viền lượn wobbly, chấm bi giấy phác thảo, nét mực vẽ tay sống động & font Mali/Patrick Hand",
    previewColors: ["#ff4d4d", "#2d5da1"],
    bgType: "paper",
    canvasBg: "#fdfbf7",
    panelFill: "#ffffff",
    panelBorder: "#2d2d2d",
    panelRadius: 24,
    isHandDrawn: true,
    shadowOffset: 6,
    shadowColor: "#2d2d2d",
    fontHeading: "'Mali', 'Patrick Hand', cursive, sans-serif",
    fontBody: "'Patrick Hand', 'Mali', cursive, sans-serif",
    titleColor: "#2d2d2d",
    subtitleColor: "#57534e",
    textPrimary: "#2d2d2d",
    textMuted: "#57534e",
    badgeBg: "#ff4d4d",
    badgeText: "#ffffff",
    dayColor: "#2d2d2d",
    dayBorderColor: "#2d2d2d",
    timeColor: "#2d5da1",
    timeBorderColor: "#d6d3d1",
    cellFill: "#ffffff",
    cellBorder: "#2d2d2d",
    cellEmptyFill: "#fffbeb", // Post-it yellow tint
    cellEmptyBorder: "#d6d3d1",
    subjectColor: "#2d2d2d",
    teacherColor: "#2d5da1", // Bút bi xanh
    highlightDefault: "#fef08a",
    uiAccentBg: "bg-red-500 text-white",
    uiCardBg: "bg-amber-50/80 border-stone-800",
    uiBorder: "border-stone-800",
  },
];
